### ISSUE TITLE
E5 first image broken

### ISSUE THREAD

**Issue by mmcdermott18** [sandicheeksx/introtowebdesign#1]
Your first image on E5 is broken. I can give you a hint that it has to do with capitalization in the file name.

Also, I don't know if you are on a Windows machine but Windows machines ignore capitalization locally which is bad because that makes your site appear to work locally and then break when you push it live.

If you are on a Mac this should have been broken for you locally too.

Last thing is the images don't need to be wrapped in paragraph elements. They can be but they don't need to be.

**Comment by sandicheeksx** [comment]
I am using Windows. I changed the file and tried to fix some things on Atom. Let me know if that fixed the issues. I can see the images when I open the link. 

https://sandicheeksx.github.io/introtowebdesign/website

**Comment by mmcdermott18** [comment]
So I think that fixed the desktop image but now the mobile image is missing for me.  My guess is it happened because you changed the capitalization of the file name. For some odd reason Github doesn’t like changing the case in file or folder names. 

The typical fix to solve this is to move the file you changed (which I think is mobileWireframe.jpg) our of your repository. Push that change so Github thinks the file is gone. Then add the file back in and push again. That typically solves the issue. 

The second thing is it looks like you changed the name of your main HTML file to website.html which breaks your link on the class site. I would change that back to index.html.

**Comment by sandicheeksx** [comment]
I followed your instructions but I cant get it to work live. It works fine when I pull the the index.html file but not through github

**Comment by mmcdermott18** [comment]
It's working for me. Is it still not working for you?

**Comment by sandicheeksx** [comment]
That's so strange! It's working for me now. It definitely was not working last night when I was messing around with it. Glad it fixed itself.
